name: Deploy to VPS using rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 95.217.158.219 >> ~/.ssh/known_hosts

    - name: Deploy code via rsync
      run: |
        rsync -avz --delete ./ root@95.217.158.219:/var/www/jamamattar/public_html/git_action